### ISSUE TITLE
streaming rows blocks http up-to 20 seconds 

### ISSUE THREAD

**Issue by devzer01** [mscdex/node-mariasql#119]
hi guys, i am not sure if this is expected behaviour or a bug. if i use the streaming row approach it seems to block `http` from sending a 2nd request. 

steps to reproduce

- run the first code snippet 
- send a request to the http server (wait 1 second)
- send a another request to the http server
- observe the mysql-server process list (you will notice that the second connection does not appear until about 20 seconds have passed 

here are some basic sample code you can reproduce the problem

```
var http = require('http');
const PORT=3000; 
var server = http.createServer(handleRequest);
var Client = require('mariasql');

function handleRequest(request, res){
    var c = new Client();
    c.connect({
        host: "localhost",
        user: "root",
        password: "",
        db: "test"
    });
    var query = 'SELECT SLEEP(30)';
    var q = c.query(query);
    var rows = [];
    q.on('result', function(res) {
        res.on('data', function(row) {
            rows.push(row);
        }).on('end', function(info) {
        });
    }).on('end', function() {
        c.end();
    });
}
server.listen(PORT, function(){
    console.log("Server listening on: http://localhost:%s", PORT);
});
```

this behaviour can only be observed when using `http`. when using `net` package the behaviour does not occur 

```
var net = require('net');
var Client = require('mariasql');
var server = net.createServer(function(socket) {
    var c = new Client();
    c.connect({
        host: "localhost",
        user: "root",
        password: "",
        db: "test"
    });
    var query = 'SELECT SLEEP(30)';
    var q = c.query(query);
    var rows = [];
    q.on('result', function(res) {
        res.on('data', function(row) {
            rows.push(row);
        }).on('end', function(info) {
        });
    }).on('end', function() {
        c.end();
    });
});

server.listen(1337, '127.0.0.1');
```

however if switched to `query(q,callback)` approach the behaviour does not occur. 

```
var http = require('http');
const PORT=3000; 
var server = http.createServer(handleRequest);
var Client = require('mariasql');

//We need a function which handles requests and send response
function handleRequest(request, res){
    var c = new Client();
    c.connect({
        host: "localhost",
        user: "root",
        password: "",
        db: "test"
    });
    var query = 'SELECT SLEEP(30)';
    c.query(query, function(err, rows) {
        if (err)
            throw err;
        res.end("hello " + util.inspect(rows));
    });
}
server.listen(PORT, function(){
});
```

once again this maybe behaviour by design when using the streaming row approach. i thought to write up here incase if anyone else ran into the same issue.

**Comment by mscdex** [comment]
This problem is unrelated to the addon and is instead about the behavior of the client (browser in your case).

One easy way to tell that the process itself is not blocked is to add a simple interval timer that does something simple like `console.log('hello world')` every second and you'll see that "hello world" is printed while the streamed query is executing.

So now that it's been determined that the process (event loop) is not being blocked, you'll find that if you use multiple browsers (instead of multiple tabs within the same browser) in parallel, that you will see http requests get answered just fine (you can also hit the server with a bunch of `curl` requests too). Also, you will further find that if you append unique parts to the url for each http request (e.g. `http://localhost/?123456`, `http://localhost/?7890`, etc.), the browser will send them immediately.

I haven't done any digging to find out the *reason* behind this behavior, but now you know it's a client-side issue and not a server-side issue.

**Comment by mscdex** [comment]
I should also note that in my testing, streaming vs. buffered queries made no difference.
