### ISSUE TITLE
Client Connections limit?

### ISSUE THREAD

**Issue by appernetic** [mscdex/node-mariasql#162]
Hi,
I have a strange issue with max client connections limit. It is by default set to 100 in my.cnf (/etc/mysql/my.cnf). But when I check the connections I have more than that. Do I need to tell the node-mariasql client where the my.conf file is? I thought that the server should handle this.

The number of connections is also never decreasing. I have the default setting: wait_timeout        = 600 which is 10 min.

I just added: read_default_file: 

```
var c = new Client({
  host: '127.0.0.1',
  db: 'myDB',
  user: 'jackass',
  charset: 'utf8',
  password: '*****',
  read_default_file: '/etc/mysql/my.cnf'
});
```

No difference.

![mariadb_appernetic](https://cloud.githubusercontent.com/assets/15160419/19330039/3b43958c-90dc-11e6-8d04-f0cd449c8399.png)

**Comment by mscdex** [comment]
The config files do not dictate the maximum number of connections, that's entirely up to your code.

[`wait_timeout`](http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout) is a server-side variable. There is a documentation issue though, as there is no `pingInterval` option or a default ping interval of any kind anymore in the most recent module versions. There are `pingInactive` and `pingWaitRes` options (currently undocumented -- not intentional) which are connection inactivity and ping response timeouts respectively, but they are not enabled by default.

So as long as you're using the most recent version of `mariasql` on npm, the connections _should_ time out after 10 minutes of inactivity with your current configuration if your `wait_timeout` is under the `[mysqld]` section, otherwise MySQL's default of 8 hours will be used.

**Comment by appernetic** [comment]
Hi,
thanks for the explanation. I assumed wrongly that it would be enough to have c.end(); as in the examples to have the connections closed.

I have it under [myslqd].
I am using v 0.2.5.

I will update to v 0.2.6 on my dev server and see if it works.

**Comment by appernetic** [comment]
Updated to v 0.2.6, restarted node server and tested with node and waited 15 minutes. No connections have timed out. I double checked that I only have a /etc/mysql/my.cnf file also with the right settings. I am using Ubuntu 14.0.4 and MariaDB 10.1.17.

**Comment by mscdex** [comment]
Have you tried querying the `wait_timeout` value from `information_schema` (both global and session variables tables) to make sure the appropriate value is in fact being used by the server?

**Comment by appernetic** [comment]
Checked now and that was problem: wait_timeout 28800

So I have to set it programmaticaly in the information_schema?

**Comment by appernetic** [comment]
I have both changed the global and session vars now. Thanks for the support! Closing
