### ISSUE TITLE
MySQL server has gone away at Error (native)

### ISSUE THREAD

**Issue by pumbac** [mscdex/node-mariasql#165]
I setup an api like this:

`var express=require(express);`
`var client=require(mariasql);`
`var config=require(../config);`
`var app=express();`

`var conn=new client(config.db);`

`var test = function(res){`
`conn.query('show now()',function(err,data){`
        `res.json(data);`
`}`
`}`

`app.get('/api',function(req, res, next) {`
`test(res);`
`});`

`... ...`

test the url 'http://localhost:3000/api' , it works.
## but after some time, node throw this **and cracked**:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: MySQL server has gone away
    at Error (native)

---

so I change the 'test' by define the conn inside it:
`var test = function(res){`
`var conn=new client(config.db);`
`conn.query('show now()',function(err,data){`
        `res.json(data);`
`}`
`conn.end();`
`}`

it still works. but when I use siege to test the performance, it soon report:

**[error]** socket: 1656551168 connection refused.: Connection refused

and node crashed again and report:

---

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Too many connections
    at Error (native)

---

and the events like end() and close() was not triggered both time.

so, what can I do to:
- stop node from crashing?
- establish the connection after its timeout?

**Comment by Nibbler999** [comment]
You need to keep the connection alive using the `pingInterval` option.

**Comment by mscdex** [comment]
You should create and use a connection pool of some kind, using a generic pooling module. Otherwise you are creating a new connection for every http request which the server probably doesn't like. You may also run out of file descriptors (especially if you are running siege on the same machine as your Express server).

As far as the error about the MySQL server going away goes, you could try enabling automatic pinging of the server to help keep the connection alive by setting `pingInactive` to the number of milliseconds to wait before sending a ping (after the connection has been idle for that long) and `pingWaitRes` to the number of millseconds to allow the server to respond before assuming the connection is dead.

The documentation is currently incorrect about these keepalive settings, `pingInterval` currently does not exist in the code.

**Comment by pumbac** [comment]
@mscdex thanks for your reply so quickly.

would you pls recommend a pooling module for mariasql? and a cache module is also needed :)

**Comment by mscdex** [comment]
I haven't used any pooling or caching modules (other than the `lru-cache` caching module used by this module), so I can't really recommend any. The only generic pooling module I recall is [`generic-pool`](https://github.com/coopernurse/node-pool), so you could start there I suppose. For caching it really depends on your needs and the underlying algorithm, but there are plenty of generic caching modules on npm, you just have to search around.

**Comment by pumbac** [comment]
@mscdex thanks again.
